### ISSUE TITLE
Llama2 supported？

### ISSUE THREAD

**Issue by skykiseki** [yuhuixu1993/qa-lora#19]
1. Any performance result of llama2-series models？
2. Does QA-Lora work on llama2? It seems not to converge(refers to other issues).

**Comment by xxw11** [comment]
1.QA-LoRA supports LLaMA2, and specific performance details can be referred to in Table 4 of the paper.

![image](https://github.com/yuhuixu1993/qa-lora/assets/55141908/b8d2e430-f02c-4226-8375-dbe9a6ec0234)

2.The issues with data type conflicts and loss not converging have been resolved, and you can try again.

**Comment by skykiseki** [comment]
> 1.QA-LoRA supports LLaMA2, and specific performance details can be referred to in Table 4 of the paper.
> 
> ![image](https://private-user-images.githubusercontent.com/55141908/312417920-b8d2e430-f02c-4226-8375-dbe9a6ec0234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMzUzNTIsIm5iZiI6MTcxMDMzNTA1MiwicGF0aCI6Ii81NTE0MTkwOC8zMTI0MTc5MjAtYjhkMmU0MzAtZjAyYy00MjI2LTgzNzUtZGJlOWE2ZWMwMjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDEzMDQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OWU5YTJkYzcyMzc5YzU4NTAzNDVlMWMyM2ZiNGJiZmY2NGQ3MWM1MWMxM2NjZjM1ODM5YjQxMDYwZGEyMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sPCNGxeeSviHAx9bcNG-bs5lL9CzvgWYo9dhA3PNcSk)
> 
> 2.The issues with data type conflicts and loss not converging have been resolved, and you can try again.

thx

**Comment by wenjingk-xilinx** [comment]
Hi @xxw11 @skykiseki , I tried to train llama2-7b, but the loss becomes 0 after some iterations , could you help to have a look?

> LlamaGPTQForCausalLM supports injecting fused attention but not enables this time. If you are training adapters, you must also disable fused attention injection when loading quantized base model at inference time, otherwise adapters may not be added to base model properly. If you are loading adapters to do inference, you can reference to adapter's config file to check whether the adapters are trained using base model that not enable fused attention injection.
  warnings.warn(
loading base model ./llama2-7b-3bit-128g/...
trainable params: 10950144.0 || all params: 1160871936 || trainable: 0.9432689050724024
loaded model
Splitting train dataset in train and validation according to `eval_dataset_size`
torch.float16 132431872 0.11407965675896915
torch.int32 809500672 0.6973212521523132
torch.float32 218939392 0.18859909108871764
  5%|████████                                                                                                                                                         | 250/5000 [3:04:18<27:27:55, 20.82s/it]
{'loss': 1.4567, 'learning_rate': 0.0002, 'epoch': 0.0}
{'loss': 1.4625, 'learning_rate': 0.0002, 'epoch': 0.01}
{'loss': 1.3844, 'learning_rate': 0.0002, 'epoch': 0.01}
{'loss': 1.4193, 'learning_rate': 0.0002, 'epoch': 0.01}
{'loss': 1.4123, 'learning_rate': 0.0002, 'epoch': 0.02}
{'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.02}
{'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.02}
{'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.03}
{'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.03}
{'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.03}
{'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.03}
{'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.04}
{'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.04}

With exactly the same script, I can train llama-7b. Seems wierd.

**Comment by xxw11** [comment]
> Hi @xxw11 @skykiseki , I tried to train llama2-7b, but the loss becomes 0 after some iterations , could you help to have a look?
> 
> > LlamaGPTQForCausalLM supports injecting fused attention but not enables this time. If you are training adapters, you must also disable fused attention injection when loading quantized base model at inference time, otherwise adapters may not be added to base model properly. If you are loading adapters to do inference, you can reference to adapter's config file to check whether the adapters are trained using base model that not enable fused attention injection.
> > warnings.warn(
> > loading base model ./llama2-7b-3bit-128g/...
> > trainable params: 10950144.0 || all params: 1160871936 || trainable: 0.9432689050724024
> > loaded model
> > Splitting train dataset in train and validation according to `eval_dataset_size`
> > torch.float16 132431872 0.11407965675896915
> > torch.int32 809500672 0.6973212521523132
> > torch.float32 218939392 0.18859909108871764
> > 5%|████████                                                                                                                                                         | 250/5000 [3:04:18<27:27:55, 20.82s/it]
> > {'loss': 1.4567, 'learning_rate': 0.0002, 'epoch': 0.0}
> > {'loss': 1.4625, 'learning_rate': 0.0002, 'epoch': 0.01}
> > {'loss': 1.3844, 'learning_rate': 0.0002, 'epoch': 0.01}
> > {'loss': 1.4193, 'learning_rate': 0.0002, 'epoch': 0.01}
> > {'loss': 1.4123, 'learning_rate': 0.0002, 'epoch': 0.02}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.02}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.02}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.03}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.03}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.03}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.03}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.04}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.04}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.04}
> 
> With exactly the same script, I can train llama-7b. Seems wierd.


Hi, have you tried following the latest environment setup tutorial? Could you provide me with more information, such as the CUDA version and the specific content of the script?

**Comment by wenjingk-xilinx** [comment]
Hi @yuhuixu1993 , I couldn't successfully create the conda environment following the latest setup tutorial, I met the problem following:
$

>  conda install pytorch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 pytor
> ch-cuda=12.1 -c pytorch -c nvidia
> Collecting package metadata (current_repodata.json): done
> Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
> Collecting package metadata (repodata.json): done
> Solving environment: done
> 
> 
> ==> WARNING: A newer version of conda exists. <==
>   current version: 23.7.4
>   latest version: 24.3.0
> 
> Please update conda by running
> 
>     $ conda update -n base -c defaults conda
> 
> Or to minimize the number of packages updated during conda update use
> 
>      conda install conda=24.3.0
> 
> 
> 
> ## Package Plan ##
> 
>   environment location: /proj/ossdataset1/wenjingk/anaconda3/envs/qalora3
> 
>   added / updated specs:
>     - pytorch-cuda=12.1
>     - pytorch==2.2.0
>     - torchaudio==2.2.0
>     - torchvision==0.17.0
> 
> 
> The following NEW packages will be INSTALLED:
> 
>   blas               pkgs/main/linux-64::blas-1.0-mkl
>   brotli-python      pkgs/main/linux-64::brotli-python-1.0.9-py38h6a678d5_7
>   bzip2              pkgs/main/linux-64::bzip2-1.0.8-h5eee18b_5
>   certifi            pkgs/main/linux-64::certifi-2024.2.2-py38h06a4308_0
>   charset-normalizer pkgs/main/noarch::charset-normalizer-2.0.4-pyhd3eb1b0_0
>   cuda-cudart        nvidia/linux-64::cuda-cudart-12.1.105-0
>   cuda-cupti         nvidia/linux-64::cuda-cupti-12.1.105-0
>   cuda-libraries     nvidia/linux-64::cuda-libraries-12.1.0-0
>   cuda-nvrtc         nvidia/linux-64::cuda-nvrtc-12.1.105-0
>   cuda-nvtx          nvidia/linux-64::cuda-nvtx-12.1.105-0
>   cuda-opencl        nvidia/linux-64::cuda-opencl-12.4.99-0
>   cuda-runtime       nvidia/linux-64::cuda-runtime-12.1.0-0
>   .....
>   zstd               pkgs/main/linux-64::zstd-1.5.5-hc292b87_0
> 
> 
> Proceed ([y]/n)? y
> 
> 
> Downloading and Extracting Packages
> 
> Preparing transaction: done
> Verifying transaction: failed
> 
> CondaVerificationError: The package for pytorch located at /proj/ossdataset1/wenjingk/anaconda3/pkgs/pytorch-2.2.0-py3.8_cuda12.1_cudnn8.9.2_0
> appears to be corrupted. The path 'lib/python3.8/site-packages/functorch/_C.cpython-38-x86_64-linux-gnu.so'
> specified in the package manifest cannot be found.
> 
> CondaVerificationError: The package for pytorch located at /proj/ossdataset1/wenjingk/anaconda3/pkgs/pytorch-2.2.0-py3.8_cuda12.1_cudnn8.9.2_0
> appears to be corrupted. The path 'lib/python3.8/site-packages/torch-2.2.0-py3.8.egg-info/PKG-INFO'
> specified in the package manifest cannot be found.
> 
> CondaVerificationError: The package for pytorch located at /proj/ossdataset1/wenjingk/anaconda3/pkgs/pytorch-2.2.0-py3.8_cuda12.1_cudnn8.9.2_0
> appears to be corrupted. The path 'lib/python3.8/site-packages/torch-2.2.0-py3.8.egg-info/SOURCES.txt'
> specified in the package manifest cannot be found.
> 
> CondaVerificationError: The package for pytorch located at /proj/ossdataset1/wenjingk/anaconda3/pkgs/pytorch-2.2.0-py3.8_cuda12.1_cudnn8.9.2_0
> appears to be corrupted. The path 'lib/python3.8/site-packages/torch-2.2.0-py3.8.egg-info/dependency_links.txt'
> specified in the package manifest cannot be found.
> appears to be corrupted. The path 'lib/python3.8/site-packages/torch-2.2.0-py3.8.egg-info/dependency_links.txt'                               
> specified in the package manifest cannot be found.
> ...


So I still use the environment following the last tutorial,  my environment setting is:

> $ conda list
> # packages in environment at /proj/ossdataset1/wenjingk/anaconda3/envs/qalora:
> #
> # Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                        main
> _openmp_mutex             5.1                       1_gnu
> absl-py                   2.1.0                    pypi_0    pypi
> accelerate                0.21.0                   pypi_0    pypi
> aiohttp                   3.9.1                    pypi_0    pypi
> aiosignal                 1.3.1                    pypi_0    pypi
> appdirs                   1.4.4                    pypi_0    pypi
> asttokens                 2.4.1                    pypi_0    pypi
> async-timeout             4.0.3                    pypi_0    pypi
> attrs                     23.2.0                   pypi_0    pypi
> auto-gptq                 0.3.0                    pypi_0    pypi
> backcall                  0.2.0                    pypi_0    pypi
> bert-score                0.3.13                   pypi_0    pypi
> bitsandbytes              0.42.0                   pypi_0    pypi
> ca-certificates           2023.12.12           h06a4308_0
> certifi                   2023.11.17               pypi_0    pypi
> charset-normalizer        3.3.2                    pypi_0    pypi
> click                     8.1.7                    pypi_0    pypi
> cmake                     3.25.0                   pypi_0    pypi
> contourpy                 1.1.1                    pypi_0    pypi
> cycler                    0.12.1                   pypi_0    pypi
> datasets                  2.16.1                   pypi_0    pypi
> decorator                 5.1.1                    pypi_0    pypi
> dill                      0.3.7                    pypi_0    pypi
> docker-pycreds            0.4.0                    pypi_0    pypi
> evaluate                  0.4.0                    pypi_0    pypi
> executing                 2.0.1                    pypi_0    pypi
> filelock                  3.13.1                   pypi_0    pypi
> fonttools                 4.47.2                   pypi_0    pypi
> frozenlist                1.4.1                    pypi_0    pypi
> fsspec                    2023.10.0                pypi_0    pypi
> gitdb                     4.0.11                   pypi_0    pypi
> gitpython                 3.1.41                   pypi_0    pypi
> huggingface-hub           0.20.2                   pypi_0    pypi
> idna                      3.6                      pypi_0    pypi
> importlib-resources       6.1.1                    pypi_0    pypi
> ipdb                      0.13.13                  pypi_0    pypi
> ipython                   8.12.3                   pypi_0    pypi
> jedi                      0.19.1                   pypi_0    pypi
> jinja2                    3.1.3                    pypi_0    pypi
> joblib                    1.3.2                    pypi_0    pypi
> kiwisolver                1.4.5                    pypi_0    pypi
> ld_impl_linux-64          2.38                 h1181459_1
> libffi                    3.4.4                h6a678d5_0
> libgcc-ng                 11.2.0               h1234567_1
> libgomp                   11.2.0               h1234567_1
> libstdcxx-ng              11.2.0               h1234567_1
> lit                       15.0.7                   pypi_0    pypi
> markupsafe                2.1.3                    pypi_0    pypi
> matplotlib                3.7.4                    pypi_0    pypi
> matplotlib-inline         0.1.6                    pypi_0    pypi
> mpmath                    1.3.0                    pypi_0    pypi
> multidict                 6.0.4                    pypi_0    pypi
> multiprocess              0.70.15                  pypi_0    pypi
> ncurses                   6.4                  h6a678d5_0
> networkx                  3.1                      pypi_0    pypi
> nltk                      3.8.1                    pypi_0    pypi
> numpy                     1.24.4                   pypi_0    pypi
> nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
> nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
> dill                      0.3.7                    pypi_0    pypi
> docker-pycreds            0.4.0                    pypi_0    pypi
> evaluate                  0.4.0                    pypi_0    pypi
> executing                 2.0.1                    pypi_0    pypi
> filelock                  3.13.1                   pypi_0    pypi
> fonttools                 4.47.2                   pypi_0    pypi
> frozenlist                1.4.1                    pypi_0    pypi
> fsspec                    2023.10.0                pypi_0    pypi
> gitdb                     4.0.11                   pypi_0    pypi
> gitpython                 3.1.41                   pypi_0    pypi
> huggingface-hub           0.20.2                   pypi_0    pypi
> idna                      3.6                      pypi_0    pypi
> importlib-resources       6.1.1                    pypi_0    pypi
> ipdb                      0.13.13                  pypi_0    pypi
> ipython                   8.12.3                   pypi_0    pypi
> jedi                      0.19.1                   pypi_0    pypi
> jinja2                    3.1.3                    pypi_0    pypi
> joblib                    1.3.2                    pypi_0    pypi
> kiwisolver                1.4.5                    pypi_0    pypi
> ld_impl_linux-64          2.38                 h1181459_1
> libffi                    3.4.4                h6a678d5_0
> libgcc-ng                 11.2.0               h1234567_1
> libgomp                   11.2.0               h1234567_1
> libstdcxx-ng              11.2.0               h1234567_1
> lit                       15.0.7                   pypi_0    pypi
> markupsafe                2.1.3                    pypi_0    pypi
> matplotlib                3.7.4                    pypi_0    pypi
> matplotlib-inline         0.1.6                    pypi_0    pypi
> mpmath                    1.3.0                    pypi_0    pypi
> multidict                 6.0.4                    pypi_0    pypi
> multiprocess              0.70.15                  pypi_0    pypi
> ncurses                   6.4                  h6a678d5_0
> networkx                  3.1                      pypi_0    pypi
> nltk                      3.8.1                    pypi_0    pypi
> numpy                     1.24.4                   pypi_0    pypi
> nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
> nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
> dill                      0.3.7                    pypi_0    pypi
> docker-pycreds            0.4.0                    pypi_0    pypi
> evaluate                  0.4.0                    pypi_0    pypi
> executing                 2.0.1                    pypi_0    pypi
> filelock                  3.13.1                   pypi_0    pypi
> fonttools                 4.47.2                   pypi_0    pypi
> frozenlist                1.4.1                    pypi_0    pypi
> fsspec                    2023.10.0                pypi_0    pypi
> gitdb                     4.0.11                   pypi_0    pypi
> gitpython                 3.1.41                   pypi_0    pypi
> huggingface-hub           0.20.2                   pypi_0    pypi
> idna                      3.6                      pypi_0    pypi
> importlib-resources       6.1.1                    pypi_0    pypi
> ipdb                      0.13.13                  pypi_0    pypi
> ipython                   8.12.3                   pypi_0    pypi
> jedi                      0.19.1                   pypi_0    pypi
> jinja2                    3.1.3                    pypi_0    pypi
> joblib                    1.3.2                    pypi_0    pypi
> kiwisolver                1.4.5                    pypi_0    pypi
> ld_impl_linux-64          2.38                 h1181459_1
> libffi                    3.4.4                h6a678d5_0
> libgcc-ng                 11.2.0               h1234567_1
> libgomp                   11.2.0               h1234567_1
> libstdcxx-ng              11.2.0               h1234567_1
> lit                       15.0.7                   pypi_0    pypi
> markupsafe                2.1.3                    pypi_0    pypi
> matplotlib                3.7.4                    pypi_0    pypi
> matplotlib-inline         0.1.6                    pypi_0    pypi
> mpmath                    1.3.0                    pypi_0    pypi
> multidict                 6.0.4                    pypi_0    pypi
> multiprocess              0.70.15                  pypi_0    pypi
> ncurses                   6.4                  h6a678d5_0
> networkx                  3.1                      pypi_0    pypi
> nltk                      3.8.1                    pypi_0    pypi
> numpy                     1.24.4                   pypi_0    pypi
> nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
> nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
> nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi                                                                              [37/1976]
> nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
> nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
> nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
> nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
> nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
> nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
> nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
> nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
> nvidia-nccl-cu12          2.18.1                   pypi_0    pypi
> nvidia-nvjitlink-cu12     12.3.101                 pypi_0    pypi
> nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
> openssl                   3.0.12               h7f8727e_0
> packaging                 23.2                     pypi_0    pypi
> pandas                    2.0.3                    pypi_0    pypi
> parso                     0.8.3                    pypi_0    pypi
> pathtools                 0.1.2                    pypi_0    pypi
> peft                      0.4.0                    pypi_0    pypi
> pexpect                   4.9.0                    pypi_0    pypi
> pickleshare               0.7.5                    pypi_0    pypi
> pillow                    10.2.0                   pypi_0    pypi
> pip                       23.3.1           py38h06a4308_0
> prompt-toolkit            3.0.43                   pypi_0    pypi
> protobuf                  3.20.3                   pypi_0    pypi
> psutil                    5.9.7                    pypi_0    pypi
> ptyprocess                0.7.0                    pypi_0    pypi
> pure-eval                 0.2.2                    pypi_0    pypi
> pyarrow                   14.0.2                   pypi_0    pypi
> pyarrow-hotfix            0.6                      pypi_0    pypi
> pygments                  2.17.2                   pypi_0    pypi
> pyparsing                 3.1.1                    pypi_0    pypi
> python                    3.8.18               h955ad1f_0
> python-dateutil           2.8.2                    pypi_0    pypi
> pytz                      2023.3.post1             pypi_0    pypi
> pyyaml                    6.0.1                    pypi_0    pypi
> readline                  8.2                  h5eee18b_0
> regex                     2023.12.25               pypi_0    pypi
> requests                  2.31.0                   pypi_0    pypi
> responses                 0.18.0                   pypi_0    pypi
> rouge                     1.0.1                    pypi_0    pypi
> rouge-score               0.1.2                    pypi_0    pypi
> safetensors               0.4.1                    pypi_0    pypi
> scikit-learn              1.2.2                    pypi_0    pypi
> scipy                     1.10.1                   pypi_0    pypi
> sentencepiece             0.1.99                   pypi_0    pypi
> sentry-sdk                1.39.2                   pypi_0    pypi
> setproctitle              1.3.3                    pypi_0    pypi
> setuptools                68.2.2           py38h06a4308_0
> six                       1.16.0                   pypi_0    pypi
> smmap                     5.0.1                    pypi_0    pypi
> sqlite                    3.41.2               h5eee18b_0
> stack-data                0.6.3                    pypi_0    pypi
> sympy                     1.12                     pypi_0    pypi
> threadpoolctl             3.2.0                    pypi_0    pypi
> tk                        8.6.12               h1ccaba5_0
> tokenizers                0.13.3                   pypi_0    pypi
> tomli                     2.0.1                    pypi_0    pypi
> torch                     2.0.1+cu117              pypi_0    pypi
> torchaudio                2.0.2+cu117              pypi_0    pypi
> torchvision               0.15.2+cu117             pypi_0    pypi
> tqdm                      4.66.1                   pypi_0    pypi
> traitlets                 5.14.2                   pypi_0    pypi
> transformers              4.31.0                   pypi_0    pypi
> triton                    2.0.0                    pypi_0    pypi
> typing-extensions         4.9.0                    pypi_0    pypi
> tzdata                    2023.4                   pypi_0    pypi
> urllib3                   2.1.0                    pypi_0    pypi
> wandb                     0.15.2                   pypi_0    pypi
> wcwidth                   0.2.13                   pypi_0    pypi
> wheel                     0.41.2           py38h06a4308_0
> xxhash                    3.4.1                    pypi_0    pypi
> xz                        5.4.5                h5eee18b_0
> yarl                      1.9.4                    pypi_0    pypi
> zipp                      3.17.0                   pypi_0    pypi
> zlib                      1.2.13               h5eee18b_0

**Comment by wenjingk-xilinx** [comment]
my cuda version is 
> Cuda compilation tools, release 11.8, V11.8.89
> Build cuda_11.8.r11.8/compiler.31833905_0

My script:

> python qalora.py --pretrained_model_path huggyllama/llama-7b \
>     --model_path ./llama-7b-4bit-128groupsize/ \
>     --warmup_steps 300 \
>     --bits ${w_bit} \
>     --output_dir ./output/$save_name \
>     --dataset alpaca \
>     --do_train True \
>     --do_eval True \
>     --do_mmlu_eval True \
>     --source_max_len 384 \
>     --target_max_len 128 \
>     --per_device_train_batch_size 8 \
>     --per_device_eval_batch_size 4 \
>     --gradient_accumulation_steps 2 \
>     --logging_steps 10 \
>     --max_steps 10000 \
>     --save_strategy steps \
>     --data_seed 42 \
>     --save_steps 1000 \
>     --save_total_limit 40 \
>     --evaluation_strategy steps \
>     --eval_dataset_size 1024 \
>     --max_eval_samples 10 \
>     --eval_steps 1000 \
>     --optim paged_adamw_32bit

**Comment by JiaangL** [comment]
> Hi @xxw11 @skykiseki , I tried to train llama2-7b, but the loss becomes 0 after some iterations , could you help to have a look?
> 
> > LlamaGPTQForCausalLM supports injecting fused attention but not enables this time. If you are training adapters, you must also disable fused attention injection when loading quantized base model at inference time, otherwise adapters may not be added to base model properly. If you are loading adapters to do inference, you can reference to adapter's config file to check whether the adapters are trained using base model that not enable fused attention injection.
> > warnings.warn(
> > loading base model ./llama2-7b-3bit-128g/...
> > trainable params: 10950144.0 || all params: 1160871936 || trainable: 0.9432689050724024
> > loaded model
> > Splitting train dataset in train and validation according to `eval_dataset_size`
> > torch.float16 132431872 0.11407965675896915
> > torch.int32 809500672 0.6973212521523132
> > torch.float32 218939392 0.18859909108871764
> > 5%|████████                                                                                                                                                         | 250/5000 [3:04:18<27:27:55, 20.82s/it]
> > {'loss': 1.4567, 'learning_rate': 0.0002, 'epoch': 0.0}
> > {'loss': 1.4625, 'learning_rate': 0.0002, 'epoch': 0.01}
> > {'loss': 1.3844, 'learning_rate': 0.0002, 'epoch': 0.01}
> > {'loss': 1.4193, 'learning_rate': 0.0002, 'epoch': 0.01}
> > {'loss': 1.4123, 'learning_rate': 0.0002, 'epoch': 0.02}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.02}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.02}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.03}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.03}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.03}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.03}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.04}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.04}
> > {'loss': 0.0, 'learning_rate': 0.0002, 'epoch': 0.04}
> 
> With exactly the same script, I can train llama-7b. Seems wierd.

Hi @wenjingk-xilinx, I am facing the same issue. The loss is zero when finetuning llama2-7b. Have you been able to solve this problem yet?
