### ISSUE TITLE
 Request for Replication Script for LLaMA 7B on MMLU

### ISSUE THREAD

**Issue by xxw11** [yuhuixu1993/qa-lora#25]
Hi,

I'm trying to replicate the LLaMA 7B model's performance on the MMLU benchmark as reported in your paper but am seeing significant differences in results. Could you share the exact scripts or steps you used for LLaMA 7B? Access to these would be incredibly helpful for accurately reproducing the results.

Thanks for your help

**Comment by xxw11** [comment]
This issue has been resolved. After getting in touch with the author, he provided some excellent suggestions. Thanks to the author.

**Comment by xxw11** [comment]
This issue has been resolved. After getting in touch with the author, he provided some excellent suggestions. Thanks a lot.

**Comment by wenjingk-xilinx** [comment]
> This issue has been resolved. After getting in touch with the author, he provided some excellent suggestions. Thanks a lot.

Hi @xxw11 , could you please share the configuration for reproduce LLAMA7b? Thanks a lot!
