### ISSUE TITLE
Question about "merge.py"

### ISSUE THREAD

**Issue by freeSoul-SNU** [yuhuixu1993/qa-lora#38]
@yuhuixu1993 
Hello, I believe this research is remarkable.
(It's the same issue metioned here: https://github.com/yuhuixu1993/qa-lora/issues/15#issue-2016233176)

I have a question regarding the merging of fine-tuning adapters. I previously inquired about an issue where merging doesn't work due to dimension mismatch, but I haven't received a response, so I'm asking again.

When I used AutoGPTQ version 0.3.0 to quantize the Llama-7B model, I found that the dimensions of qzeros were calculated to be [128, 512], whereas the scales had a size of [128, 4096].

**1. I think the dimensions of qzeros and scales should be the same, but I'm curious why they are different. It seems that the merge isn't working due to this dimension mismatch.
2. Currently, qzeros are in float16 (though I'm not sure why, and all the values are inf). Could you share how to convert them so that the merge works?**

Thank you.

**Comment by peterwan1** [comment]
I've solved this problem. You need to decode qzeros into zeros before merging. You can refer to codes in auto_gptq/nn_modules/qlinear/qlinear_cuda.py to do this. You also need to change codes in auto_gptq(refer to a new autogptq branch in another issue ) before evaluation because you only need to decode qweights at this time.

**Comment by freeSoul-SNU** [comment]
> I've solved this problem. You need to decode qzeros into zeros before merging. You can refer to codes in auto_gptq/nn_modules/qlinear/qlinear_cuda.py to do this. You also need to change codes in auto_gptq(refer to a new autogptq branch in another issue ) before evaluation because you only need to decode qweights at this time.

@peterwan1 
Thank you for your response!
Could you let me know if you are using version 0.3.0 of AutoGPTQ and whether you have also installed Triton? In my case, when I used version 0.3.0 of AutoGPTQ for quantization, the qzeros values were stored as float16, and all the values were saved as inf, so I’m asking about this.

**Comment by peterwan1** [comment]
yes, I use autogptq-0.3.0, and I set use_triton=False because the loss is 0 when  I use triton.
After quantization, and before decoding, qzeros values are stored in INT32, like below:
tensor([[2004318071, 2004318071, 2004318071,  ..., 2004318071, 2004318071,
         2004318071],
        [2004318071, 2004318071, 2004318071,  ..., 2004318071, 2004318071,
         2004318071],
        [2004318071, 2004318071, 2004318071,  ..., 2004318071, 2004318071,
         2004318071],
        ...,
        [2004318071, 2004318071, 2004318071,  ..., 2004318071, 2004318071,
         2004318071],
        [2004318071, 2004318071, 2004318071,  ..., 2004318071, 2004318071,
         2004318071],
        [2004318071, 2004318071, 2004318071,  ..., 2004318071, 2004318071,
         2004318071]], dtype=torch.int32)

**Comment by freeSoul-SNU** [comment]
> yes, I use autogptq-0.3.0, and I set use_triton=False because the loss is 0 when I use triton. After quantization, and before decoding, qzeros values are stored in INT32, like below: tensor([[2004318071, 2004318071, 2004318071, ..., 2004318071, 2004318071, 2004318071], [2004318071, 2004318071, 2004318071, ..., 2004318071, 2004318071, 2004318071], [2004318071, 2004318071, 2004318071, ..., 2004318071, 2004318071, 2004318071], ..., [2004318071, 2004318071, 2004318071, ..., 2004318071, 2004318071, 2004318071], [2004318071, 2004318071, 2004318071, ..., 2004318071, 2004318071, 2004318071], [2004318071, 2004318071, 2004318071, ..., 2004318071, 2004318071, 2004318071]], dtype=torch.int32)

Thank you for reply! I found the bug in my code.

**Comment by lzzxcok** [comment]
@freeSoul-SNU Could you tell me how did you solve this bug

**Comment by davidray222** [comment]
@peterwan1  @freeSoul-SNU 
May I ask how you solve the merging problem? Thank you for your guidance!!
